/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GovRouteImport } from './routes/gov'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IrrigateRouteImport } from './routes/irrigate'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as PricingRouteImport } from './routes/pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GovRoute = GovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigateRoute = IrrigateRouteImport.update({
  id: '/irrigate',
  path: '/irrigate',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/contact': typeof ContactRoute
  '/gov': typeof GovRoute
  '/household': typeof HouseholdRoute
  '/how-it-works': typeof HowItWorksRoute
  '/irrigate': typeof IrrigateRoute
  '/metrics': typeof MetricsRoute
  '/operator': typeof OperatorRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/contact': typeof ContactRoute
  '/gov': typeof GovRoute
  '/household': typeof HouseholdRoute
  '/how-it-works': typeof HowItWorksRoute
  '/irrigate': typeof IrrigateRoute
  '/metrics': typeof MetricsRoute
  '/operator': typeof OperatorRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/contact': typeof ContactRoute
  '/gov': typeof GovRoute
  '/household': typeof HouseholdRoute
  '/how-it-works': typeof HowItWorksRoute
  '/irrigate': typeof IrrigateRoute
  '/metrics': typeof MetricsRoute
  '/operator': typeof OperatorRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/contact'
    | '/gov'
    | '/household'
    | '/how-it-works'
    | '/irrigate'
    | '/metrics'
    | '/operator'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/contact'
    | '/gov'
    | '/household'
    | '/how-it-works'
    | '/irrigate'
    | '/metrics'
    | '/operator'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/contact'
    | '/gov'
    | '/household'
    | '/how-it-works'
    | '/irrigate'
    | '/metrics'
    | '/operator'
    | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRoute
  ContactRoute: typeof ContactRoute
  GovRoute: typeof GovRoute
  HouseholdRoute: typeof HouseholdRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IrrigateRoute: typeof IrrigateRoute
  MetricsRoute: typeof MetricsRoute
  OperatorRoute: typeof OperatorRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov': {
      id: '/gov'
      path: '/gov'
      fullPath: '/gov'
      preLoaderRoute: typeof GovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigate': {
      id: '/irrigate'
      path: '/irrigate'
      fullPath: '/irrigate'
      preLoaderRoute: typeof IrrigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRoute,
  ContactRoute: ContactRoute,
  GovRoute: GovRoute,
  HouseholdRoute: HouseholdRoute,
  HowItWorksRoute: HowItWorksRoute,
  IrrigateRoute: IrrigateRoute,
  MetricsRoute: MetricsRoute,
  OperatorRoute: OperatorRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
